export const SET_VIEW = 'SET_VIEW';

export const GET_BEER_LIST_SUCCESS = 'GET_BEER_LIST_SUCCESS';
export const GET_BEER_LIST_FAIL = 'GET_BEER_LIST_FAIL';

export const REMOVE_BEER_SUCCESS = 'REMOVE_BEER_SUCCESS';
export const REMOVE_BEER_FAIL = 'REMOVE_BEER_FAIL';

export const SET_EDIT_BEER = 'SET_EDIT_BEER';

export const EDIT_BEER_SUCCESS = 'EDIT_BEER_SUCCESS';
export const EDIT_BEER_FAIL = 'EDIT_BEER_FAIL';

export const GET_BREWERY_LIST_SUCCESS = 'GET_BREWERY_LIST_SUCCESS';
export const GET_BREWERY_LIST_FAIL = 'GET_BREWERY_LIST_FAIL';
