function buildModal() {
  const div = $('<div>')
  $('#addModal').append(div)
  const col = $('<div>', { class: 'col-lg-4 col-md-12 col-sm-12 formContainer', id: 'addModalForm' })
  const form = $('<form>')
  const h4 = $('<h4>').text('Add a New Beer')
  const formSectionBeer = $('<div>', { class: 'form-section' })
  const formSectionBrewery = $('<div>', { class: 'form-section' })
  const formSectionRating = $('<div>', { class: 'form-section' })
  const formSectionTasting = $('<div>', { class: 'form-section' })
  const labelBeer = $('<label>', { for: 'beer' }).text('Beer:')
  const inputBeer = $('<input>', { name: 'beer', id: 'inputBeer' })
  const errorBeer = $('<div>', { id: 'beerError', class: 'error errorBeer hide' })
  const labelBrewery = $('<label>').text('Brewery:')
  const inputBrewery = $('<input>', { name: 'brewery', id: 'inputBrewery' })
  const errorBrewery = $('<div>', { id: 'breweryError', class: 'error errorBrewery hide' })
  const labelRating = $('<label>').text('Rating:')
  const inputRating = $('<input>', { name: 'rating', id: 'inputRating' })
  const errorRating = $('<div>', { id: 'ratingError', class: 'error errorRating hide' })
  const labelTasting = $('<label>').text('Tasting:')
  const inputTasting = $('<textarea>', { name: 'tasting', id: 'inputTasting' })
  const errorTasting = $('<div>', { id: 'tastingError', class: 'error errorTasting hide' })
  const buttons = $('<div>', { class: 'button-container' })
  const buttonAdd = $('<button>', { name: 'submit', id: 'submitButton', type: 'button', class: 'btn btn-primary' }).text('ADD')
  const buttonCancel = $('<button>', { name: 'cancel', id: 'cancelButton', type: 'button', class: 'btn btn-secondary' }).text('CANCEL')
  formSectionBeer.append(labelBeer)
  formSectionBeer.append(inputBeer)
  formSectionBeer.append(errorBeer)
  formSectionBrewery.append(labelBrewery)
  formSectionBrewery.append(inputBrewery)
  formSectionBrewery.append(errorBrewery)
  formSectionRating.append(labelRating)
  formSectionRating.append(inputRating)
  formSectionRating.append(errorRating)
  formSectionTasting.append(labelTasting)
  formSectionTasting.append(inputTasting)
  formSectionTasting.append(errorTasting)
  buttons.append(buttonAdd)
  buttons.append(buttonCancel)
  form.append(h4)
  form.append(formSectionBeer)
  form.append(formSectionBrewery)
  form.append(formSectionRating)
  form.append(formSectionTasting)
  form.append(buttons)
  col.append(form)
  $('#addModal').append(col)

  $('#submitButton').click(handleButtonClick)
  $('#cancelButton').click(handleButtonClick)
  $('#inputBeer').focus(handleInputFocus)
  $('#inputBrewery').focus(handleInputFocus)
  $('#inputRating').focus(handleInputFocus)
  $('#inputTasting').focus(handleInputFocus)
}
